import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import "./globals.css"
import Providers from "./providers"
import AppHeader from "@/components/AppHeader"
import AppSidebar from "@/components/AppSidebar"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
import "@fortawesome/fontawesome-svg-core/styles.css"
import { config } from "@fortawesome/fontawesome-svg-core"
config.autoAddCss = false

const nunito = Nunito({ subsets: ["latin"] })
export const metadata: Metadata = {
    title: "Melody Hub",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={nunito.className}>
                <Providers>
                    <div className="flex min-h-screen flex-col">
                        <div className="flex flex-1">
                            <div className="w-1/6">
                                <AppSidebar />
                            </div>
                            <div className="w-5/6 pb-16">
                                <AppHeader />
                                {children}
                            </div>
                        </div>
                    </div>
                    <ToastContainer
                        position="top-right"
                        autoClose={5000}
                        hideProgressBar={false}
                        newestOnTop={false}
                        closeOnClick
                        rtl={false}
                        pauseOnFocusLoss
                        draggable
                        pauseOnHover
                        theme="dark"
                    />
                </Providers>
            </body>
        </html>
    )
}
